/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import java.awt.Component;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.plaf.synth.Region;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author phamq
 */
public class formManageCustomer extends javax.swing.JInternalFrame {

    /**
     * Creates new form temp2
     */
    public static void setSize(JFrame x) {

    }

    public formManageCustomer() {
        initComponents();

        BasicInternalFrameUI bi = (BasicInternalFrameUI) this.getUI();
        bi.setNorthPane(null);
        loadDefaultData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        input_Field = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listCustomer = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(17, 43, 60));
        setOpaque(true);
        setPreferredSize(new java.awt.Dimension(1109, 680));

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(1109, 680));

        jButton4.setBackground(new java.awt.Color(0, 0, 51));
        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/search_45px.png"))); // NOI18N
        jButton4.setBorder(null);

        input_Field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                input_FieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                input_FieldKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nhập Tên Khách Hàng");

        jButton3.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Yellow"));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/maintenance_45px.png"))); // NOI18N
        jButton3.setText("Sửa");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("QUẢN LÝ KHÁCH HÀNG");

        listCustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        listCustomer.setRowHeight(160);
        jScrollPane1.setViewportView(listCustomer);

        jButton2.setBackground(new java.awt.Color(102, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/cancel_45px.png"))); // NOI18N
        jButton2.setText("Xoá");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(input_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(input_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)))
                            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2)
                        .addComponent(jButton3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void input_FieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_input_FieldKeyPressed
        loadData();
    }//GEN-LAST:event_input_FieldKeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int index = listCustomer.getSelectedRow();

        String MaND = listCustomer.getValueAt(index, 0).toString();

        processes.deleteData.DeleteUser(MaND);

        loadDefaultData();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void input_FieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_input_FieldKeyReleased
        loadData();
    }//GEN-LAST:event_input_FieldKeyReleased

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            int indexRow = listCustomer.getSelectedRow();

            System.out.println(indexRow);

            String MaKH = (String) listCustomer.getValueAt(indexRow, 0);
            String TenKH = (String) listCustomer.getValueAt(indexRow, 1);
            String TenDangNhap = (String) listCustomer.getValueAt(indexRow, 2);
            String Email = (String) listCustomer.getValueAt(indexRow, 3);
            String MatKhau = (String) listCustomer.getValueAt(indexRow, 4);
            String DiaChi = (String) listCustomer.getValueAt(indexRow, 5);
            String SoDT = (String) listCustomer.getValueAt(indexRow, 6);
            String NgaySinh = (String) listCustomer.getValueAt(indexRow, 7);
            System.out.println(MaKH);
            System.out.println(TenKH);
            

            MaKH = MaKH.replace(" ", "");

            Objects.User u = new Objects.User(MaKH, TenKH, TenDangNhap, Email, MatKhau, DiaChi, SoDT, NgaySinh);
            System.out.println("Data is+ "+u.getTenND());
            processes.updateData.updateUserByRole("KHACHHANG", u);

            JOptionPane.showMessageDialog(null, "Cập nhật thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(null, "Cập nhật thất bại!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    public void loadData() {
        String text = input_Field.getText();

        DefaultTableModel dm = (DefaultTableModel) listCustomer.getModel();

        while (dm.getRowCount() > 0) {
            dm.removeRow(0);
        }

        DefaultTableModel model = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return column != 0 && column != 2;
            }

        };

        model.addColumn("Mã khách hàng");
        model.addColumn("Tên khách hàng");
        model.addColumn("Tên đăng nhập");
        model.addColumn("Email");
        model.addColumn("Mật khẩu");

        model.addColumn("Địa chỉ");
        model.addColumn("Số điện thoại");
        model.addColumn("Ngày sinh");
        model.addColumn("CCCD_T");
        model.addColumn("CCCD_S");

        try {
            List<Objects.User> customers = new ArrayList<Objects.User>();

            customers = processes.getData.getUserContainChar(text, "KHACHHANG");
            if (customers != null) {
                for (Objects.User c : customers) {
                    model.addRow(new Object[]{
                        c.getMaND(), c.getTenND(), c.getTenTK(), c.getEmail(), c.getMatKhau(), c.getDiaChi(), c.getSoDT(), c.getNgaySinh(), c.getCMND_T(), c.getCMND_S()
                    });
                }
                System.out.println("Added all row!");
            } else {
                System.out.println("List is null");
            }

        } catch (Exception e) {
            System.out.println("List is null! " + e);
        }
        listCustomer.setModel(model);
        listCustomer.getColumnModel().getColumn(8).setCellRenderer(new ImageRender());
        listCustomer.getColumnModel().getColumn(9).setCellRenderer(new ImageRender());
    }

    public void loadDefaultData() {
        String text = "";

        DefaultTableModel dm = (DefaultTableModel) listCustomer.getModel();

        while (dm.getRowCount() > 0) {
            dm.removeRow(0);
        }

        DefaultTableModel model = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return column != 0 && column != 2;
            }
        };

        model.addColumn("Mã khách hàng");
        model.addColumn("Tên khách hàng");
        model.addColumn("Tên đăng nhập");
        model.addColumn("Email");
        model.addColumn("Mật khẩu");

        model.addColumn("Địa chỉ");
        model.addColumn("Số điện thoại");
        model.addColumn("Ngày sinh");
        model.addColumn("CCCD_T");
        model.addColumn("CCCD_S");

        try {
            List<Objects.User> customers = new ArrayList<>();

            customers = processes.getData.getUserContainChar(text, "KHACHHANG");
            if (customers != null) {
                for (Objects.User c : customers) {
                    model.addRow(new Object[]{
                        c.getMaND(), c.getTenND(), c.getTenTK(), c.getEmail(), c.getMatKhau(), c.getDiaChi(), c.getSoDT(), c.getNgaySinh(), c.getCMND_T(), c.getCMND_S()
                    });
                    System.out.println(c.getCMND_S().toString());
                }
                System.out.println("Added all row!");
            } else {
                System.out.println("List is null");
            }

        } catch (Exception e) {
            System.out.println("List is null! " + e);
        }
        listCustomer.setModel(model);
        listCustomer.getColumnModel().getColumn(8).setCellRenderer(new ImageRender());
        listCustomer.getColumnModel().getColumn(9).setCellRenderer(new ImageRender());
    }

    private class ImageRender extends DefaultTableCellRenderer {

        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {

            try {
                //String photoName = value.toString();
                BufferedImage img = (BufferedImage) value;
                ImageIcon imgIcon = new ImageIcon(new ImageIcon(img).getImage().getScaledInstance(128, 128, Image.SCALE_DEFAULT));
                return new JLabel(imgIcon);
            } catch (Exception ex) {
                Logger.getLogger(formOrder.class.getName()).log(Level.SEVERE, null, ex);
            }
            return null;

        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField input_Field;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable listCustomer;
    // End of variables declaration//GEN-END:variables
}
