/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import java.util.HashMap;
import java.sql.Connection;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author phamq
 */
public class formRevenue extends javax.swing.JInternalFrame {

    /**
     * Creates new form formFindVehicleStatus
     */
    public formRevenue() {
        initComponents();
         initComponents();
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
        LoadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        namHD = new com.toedter.calendar.JYearChooser();
        thangHD = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listDoanhThu = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(17, 43, 60));
        setForeground(java.awt.Color.pink);
        setOpaque(true);
        setPreferredSize(new java.awt.Dimension(1109, 680));
        setVisible(true);

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TRA CỨU DOANH THU");

        thangHD.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        thangHD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        thangHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                thangHDMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                thangHDMouseReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Năm");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tháng");

        jButton1.setBackground(new java.awt.Color(0, 0, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/ok_45px.png"))); // NOI18N
        jButton1.setText("Xuất hóa đơn");
        jButton1.setPreferredSize(new java.awt.Dimension(75, 45));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        listDoanhThu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(listDoanhThu);

        jButton2.setText("Tìm kiếm");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel3)
                                .addGap(11, 11, 11)
                                .addComponent(thangHD, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(namHD, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 477, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(namHD, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(thangHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String ThangHD = thangHD.getItemAt(thangHD.getSelectedIndex()).toString();
        String NamHD = String.valueOf(namHD.getValue());
        
        try{
            ExportReport(ThangHD, NamHD);
        }catch(Exception ex)
        {
            System.out.println(ex);
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void thangHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thangHDMouseClicked
        LoadData();
    }//GEN-LAST:event_thangHDMouseClicked

    private void thangHDMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thangHDMouseReleased
        LoadData();
    }//GEN-LAST:event_thangHDMouseReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        LoadData();
    }//GEN-LAST:event_jButton2ActionPerformed
    
    public void ExportReport(String ThangHD, String NamHD) {

        try {
            System.out.println("Load Report.....");
            HashMap<String, Object> map = new HashMap<String, Object>();
            map.put("ThangHD", ThangHD);
            map.put("NamHD", NamHD);
            System.out.println("Mapped....");
            JasperReport rpt = JasperCompileManager.compileReport("C:\\Users\\DELL\\Desktop\\Java\\DoAn\\JavaApplication1\\src\\Resources\\XuatDoanhThu.jrxml");
            System.out.println("Report getted!");

            Connection conn = connectDB.DBO.getOracleConnection();
            System.out.println("Connected to database!");

            try {
                JasperPrint p = (JasperPrint) JasperFillManager.fillReport(rpt, map, conn);
                System.out.println("Report mapped!");
                JasperViewer.viewReport(p, false);
            } catch (Exception e) {
                System.out.println("BUG IS" + e);
            }

        } catch (Exception ex) {
            System.out.println("Err is " + ex);
        }
    }
    
    public void LoadData()
    {
        String ThangHD = thangHD.getItemAt(thangHD.getSelectedIndex()).toString();
        String NamHD = String.valueOf(namHD.getValue());
        System.out.println("Tháng hóa đơn: "+ ThangHD);
        System.out.println("Năm hóa đơn: "+ NamHD);
        List<Objects.Revenue> listRevenue = processes.getData.getRevenue(ThangHD, NamHD);
        
        DefaultTableModel model = new DefaultTableModel()                
        {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; 
            }
        };
        
        model.addColumn("Số Hóa Đơn");
        model.addColumn("Số Hợp Đồng");
        model.addColumn("Mã nhân viên");
        model.addColumn("Ngày Hóa Đơn");
        model.addColumn("Trị Giá");
        
        for(Objects.Revenue r : listRevenue)
        {
            model.addRow(new Object[]{
            r.getSoHoaDon(),r.getSoHopDong(),r.getMaNV(),r.getNgayHoaDon(),r.getTriGia()
            });
        }
        
        listDoanhThu.setModel(model);
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment( JLabel.CENTER );
        listDoanhThu.getColumnModel().getColumn(0).setCellRenderer( centerRenderer );
        listDoanhThu.getColumnModel().getColumn(1).setCellRenderer( centerRenderer );
        listDoanhThu.getColumnModel().getColumn(2).setCellRenderer( centerRenderer );
        listDoanhThu.getColumnModel().getColumn(3).setCellRenderer( centerRenderer );
        listDoanhThu.getColumnModel().getColumn(4).setCellRenderer( centerRenderer );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable listDoanhThu;
    private com.toedter.calendar.JYearChooser namHD;
    private javax.swing.JComboBox<String> thangHD;
    // End of variables declaration//GEN-END:variables
}
